//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_ArmandoSarrionGonzalez
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Documento()
        {
            this.Personas = new HashSet<Personas>();
        }
    
        public int id_doc { get; set; }
        public string tipo { get; set; }
        public string contenido { get; set; }
        public System.DateTime fecha_llegada { get; set; }
        public System.DateTime fecha_salida { get; set; }
        public string pertenencia { get; set; }
        public Nullable<int> id_remitente { get; set; }
        public Nullable<int> id_organismo { get; set; }
    
        public virtual Organismo Organismo { get; set; }
        public virtual Remitente Remitente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Personas> Personas { get; set; }
    }
}
