//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_ArmandoSarrionGonzalez
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organismo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Organismo()
        {
            this.Documento = new HashSet<Documento>();
        }
    
        public int id_organismo { get; set; }
        public string nombre { get; set; }
        public Nullable<int> telefono { get; set; }
        public Nullable<int> telefono2 { get; set; }
        public string direccion { get; set; }
        public Nullable<int> fax { get; set; }
        public string correo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Documento> Documento { get; set; }
    }
}
