//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_ArmandoSarrionGonzalez
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona_Inscrita
    {
        public int id_persona { get; set; }
        public int tomo { get; set; }
        public int pagina { get; set; }
        public int seccion { get; set; }
    
        public virtual Personas Personas { get; set; }
    }
}
